[package]
name = "html_parser"
version = "0.6.2"
authors = ["Mathias Iversen <work@mathiasiversen.com>"]
edition = "2018"
repository = "https://github.com/mathiversen/html-parser"
license = "MIT"
description = "A simple and general purpose html/xhtml parser"
keywords = ["html", "parser", "json", "pest", "dom"]
categories = ["parsing", "web-programming"]
readme = "README.md"

[features]
default = ["serde", "sede_json"]

[dependencies]
pest = "2.1"
pest_derive = "2.1"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
structopt = "0.3.14"

[dev-dependencies]
indoc = "1.0.3"
insta = "1.3.0"
tempfile = "3.1.0"
criterion = "0.3.3"
reqwest = { version = "0.10.10", features = ["blocking"] }

[[example]]
name = "get_all_href"
path = "examples/get_all_href/main.rs"

[[bench]]
name = "bench_wikipedia"
harness = false
