[package]
name = "html_parser"
version = "0.2.2"
authors = ["Mathias Iversen <work@mathiasiversen.com>"]
edition = "2018"
repository = "https://github.com/mathiversen/html-parser"
license = "MIT"
description = "A simple and general purpose html parser, using Pest."
keywords = ["html", "parser", "json", "pest", "ast"]
categories = ["parsing", "web-programming"]
readme = "README.md"

[dependencies]
pest = "2.1"
pest_derive = "2.1"
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
indoc = "0.3"
surf = "1.0"
async-std = { version = "1.5", features = ["attributes"]}
insta = "0.16"
